### ISSUE TITLE
MCC: 5/10/2021

### ISSUE THREAD

**Issue by mccurcio** [studydash/cards#21]
## Motivation/Problem Statement 💭❓:
1.  Today I had several meetings with alwaysAI.  Therefore I spent most of today reading up and watching videos about their products.
  
---

## Today's Goal/Solution 🥅:

1. Flesh out basic info for AlwaysAI 
2. DS notes & questions

---

## Result 🍓🍌🍉:

See Day 1: https://github.com/mccurcio/60_days_of_learning

---

## Observations & Next Steps 🔭👣:

1. Prepare for *Job Accountability* meeting on Tuesday at 1PM
2. Work on *Job and contacts spreadsheet*.

**Comment by r002** [comment]
Welcome to the study group, Matt!  👋  So awesome to have you onboard!  This is great!  😀 I've gone ahead and have added you to [our study group members list](https://github.com/r002/codenewbie/issues/4).  We're at three members now and you're our first member concentrating in AI/DS/ML! 🎉  This is so awesome-- we're seriously slowly assembling our own version of **_The Avengers!_** ✊

**_Onwards and upwards!_**  🥳🚀

PS.  Just to confirm, btw, are you setting "60 days" as your goal?

**Comment by anitabe404** [comment]
Hey Matt. Glad to see you've joined us. It looks like you've taken really good notes on AlwaysAI. I hope your meetings go well. 🤞🏾
