### ISSUE TITLE
Do something productive 

### ISSUE THREAD

**Issue by JazDee** [studydash/cards#214]
I did laundry today! Woot woot!

**Comment by shazahuang** [comment]
Hahahahahahhahahahahha
Robert said you need to study!!!!!!!
Hahahahahahahahahaha

**Comment by r002** [comment]
I did not say that!  I'm very inclusive!  (For now at least...)  Doing `laundry` counts as a `daily contribution`!  👍

**Comment by JazDee** [comment]
lol….he did say “for now” 🤣
