### ISSUE TITLE
Read and Refresh on Characters

### ISSUE THREAD

**Issue by JazDee** [studydash/cards#224]
So per “everyone’s” request to do study related stuff😅😂. All day delays while waiting at the airport  I read some Characters on an app to refresh my reading skills in Mandarin Chinese.  Helps me to not forget the characters.  I think I will be doing this regularly now!  Also did some stuff for filming 🤗 might do some again tonight once I get to the hotel… 🤗

**Comment by r002** [comment]
Very nice!  👍  It's cool that you're studying Chinese and doing film stuff!  What app are you using to learn Chinese, btw?  Improving my own Chinese has long been on my `todo list`-- so much to do and so little time!  I need more hours in a day!  😤

**Comment by JazDee** [comment]
I have been downloading and uninstalling different ones!  Not a lot of good ones but as of now using Du Chinese…they have different levels too! So far it’s ok. Need something with better stories tho
