### ISSUE TITLE
I missed a day! And mad cause I studied 

### ISSUE THREAD

**Issue by JazDee** [studydash/cards#237]
So yesterday morning I was up early I read for 3 hours and then took a nap! Then got busy and forgot!

anyways, I did download a new app yesterday called Duolingo! I think I like Du Chinese better.  

Today I still did the Duolingo to give it more chance.  Woke up extra early to do it and post.  Did not read as much tho. Only 30mins
I will be busy all day today on set

**Comment by shazahuang** [comment]
Oh no! If we are too busy, sometimes it will happen. Keep going! Never give up!

**Comment by anitabe404** [comment]
I use Duolingo! But for French. The free version is a bit annoying because of the ads. I ended up paying for a year.

**Comment by JazDee** [comment]
> I use Duolingo! But for French. The free version is a bit annoying because of the ads. I ended up paying for a year.

**Comment by JazDee** [comment]
@shazahuang  yes it happens…might have days like it when I start filming all day 

@anitabe404  As of now using the free version! Trying to compare apps and see which one I like more and then pay for the 1 I like…I just watch the ads for now. At least for the most part it’s a very quick ad
