### ISSUE TITLE
MCC's Accomplishment for 5/11/2021

### ISSUE THREAD

**Issue by mccurcio** [studydash/cards#25]
## Motivation/Problem Statement 💭❓:
I spent a good part of the morning trying to fix Zoom on my Linux Mint OS. It turned out that Linux Mint did not allow some snap functionality therefore some of the drivers did not get loaded properly for Zoom to work. Once I found the best answer I was able to fix it relatively easily but NOT before cursing Zoom.

I also had my Job Accountability meeting today where we discussed Linkedin profiles. If anyone is interested the video link is on my day 2 notes page. I feel that I have so much work to do and will not catch up in time. lol

https://github.com/mccurcio/60_days_of_learning/blob/main/02_linkedin_resume_work.md

---

## Today's Goal/Solution 🥅:
Working on my computer job search...

---

## Result 🍓🍌🍉:
0.1% of all my work was completed.

---

## Observations & Next Steps 🔭👣:
Try and take over the world...
![](https://cdn.wallpapersafari.com/68/31/9Rf2Wh.jpg)

---

## Extra/Fun (Optional) 🎈🎉🥳:
Today I hung out with my friend in the morning for a little while. We sat in the car and watched the birds at Oyster Pond. ;)
https://wnavprd.blob.core.windows.net/images/photos/oysterpond3-b.jpg

**Comment by r002** [comment]
Oyster Pond looks very peaceful! Nice! 🙂  I too sat in my car today; listened to podcasts while eating donuts and drinking coffee in the afternoon.  No pond though... just in a parking lot!  😂

**Comment by anitabe404** [comment]
Lolz, I approve of your next steps. And also, I think we all feel like there's just not enough time in the day to do all the things. I just have to laugh at all the random things that don't cooperate.
