### ISSUE TITLE
Keep Pushin' - 5/13/21

### ISSUE THREAD

**Issue by mccurcio** [studydash/cards#32]
## Motivation/Problem Statement:
Working on Python

---

## Today's Goal/Solution:
Getting back to working on:
- Monetizing Machine Learning by Manuel Amunategui & Mehdi Roopaei

---

## Result:
Had my Job Accountability meeting. 

---

## Observations & Next Steps:
**Keep Pushin'**

---

## References 🔗:
Link any useful resources you may have found throughout the day.

---

## Extra/Fun (Optional) 🎈🎉🥳:
Went to the CVS today! Ooooo, big day out, lol

**Comment by r002** [comment]
CVS is awesome!  I love using their **_"40% off one item"_** coupons-- they have totally mastered the art of luring in shoppers with coupon mailers/gamification! 😀

**Comment by mccurcio** [comment]
That and receipts that are a mile long. lol

**Comment by r002** [comment]
Sign up for email receipts!  Save some trees! 🌳🌲🎄🎋🌴😁
(And you still get the same coupons and 'CVS Bucks/Points' in the email!)
