### ISSUE TITLE
MCC: Python Django Using Anaconda (5/14)

### ISSUE THREAD

**Issue by mccurcio** [studydash/cards#35]
## Motivation/Problem Statement 💭❓:
I am learning Django

---

## Today's Goal/Solution 🥅:
Today was an errand day I had a bunch of small things to do so I only got about couple of hours of Django worked on.

---

## Result 🍓🍌🍉:
TBA

## Extra/Fun (Optional) 🎈🎉🥳:
Went to Mac's Seafood and got take-out cod fish and chips for dinner. ;)

**Comment by anitabe404** [comment]
Now I'm hungry. Lolz. I love how you said you _**only a couple hours**_. A couple of hours is a lot to me. LOL

**Comment by mccurcio** [comment]
Yeah, maybe over estimated that time window. ;p
