### ISSUE TITLE
MCC: Life is like swimming in the ocean, up & down (5/15)

### ISSUE THREAD

**Issue by mccurcio** [studydash/cards#37]
## Motivation/Problem Statement 💭❓:
I am working on an introduction for a Kaggle notebook.
The topic is normalization and standardization of data sets.

---

## Today's Goal/Solution 🥅:
*Hey Kids*, Today's goal was to sell my condo. Oh, did I tell you I am doing that too...

---

## Result 🍓🍌🍉:
Finished the first draft of the Kaggle Introduction. 

---

## References 🔗:
https://www.kaggle.com/neomatrix369/normalising-a-distribution/comments#1307340

---

## Extra/Fun (Optional) 🎈🎉🥳:

Made very simple homemade pizza. 
Are you starting to see a pattern here? 
Big foodie!

**Comment by r002** [comment]
Condo selling!  Wow, congrats!  😀

Also:  Kaggle!  So cool!  Two years ago, I was part of a Meetup group here in Cincinnati and for fun, we'd tackled [the Kaggle Titanic challenge](https://www.kaggle.com/c/titanic/overview).

It was cool!  I remember enjoying it a lot.  Ultimately, my interests returned to web/app dev (from data science/machine learning) but I remember it was a good time.

I logged back into my account this morning though and found this-- my best submission!  `Sep 27, 2019`!  (A lifetime ago! 😄)

![image](https://user-images.githubusercontent.com/45280066/118403491-8d4f2780-b63c-11eb-8d73-7fe72cf172f7.png)

**Comment by mccurcio** [comment]
Hi Robert,
I should have been more specific. I am attempting to sell...
This is a horsh of another color. Lolz
