### ISSUE TITLE
Meetings Day (5/18)

### ISSUE THREAD

**Issue by mccurcio** [studydash/cards#47]
## Motivation/Problem Statement 💭❓:
I had a discussion with a group in the UK about their educational platform. Followed by a meeting with my Job Accountability group. Then a discussion on surveying and Data Science using drones. Extremely cool shite.

---

## Today's Goal/Solution 🥅:
na

---

## Result 🍓🍌🍉:
Not sure

---

## Observations & Next Steps 🔭👣:
I need to fine tune my Linkedin and resume site based on Job meeting comments.

---

## Extra/Fun (Optional) 🎈🎉🥳:
It was me' dad's b-day today. He decided that take out sushi was the way to go. Pretty darn good! 🌎😀

**Comment by r002** [comment]
Keeping the streak alive!  Nice!  Haha, just ten minutes ago, I was thinking:  "Where'd the study group go?"  😂

Should've never doubted!  😅😌

Happy birthday to your dad!  🎂  Awesome!  (Sushi rocks! 🍣🍥)  Lots of family stuff today!  So cool!  😀
