### ISSUE TITLE
Writing an Article(5/21)

### ISSUE THREAD

**Issue by mccurcio** [studydash/cards#54]
## Today's Goal/Solution 🥅:
I am writing a very basic article on R.

---

## Result 🍓🍌🍉:
The fruits of your labor! Screenshots, videos, text, welcome!

---

## Observations & Next Steps 🔭👣:
What are some conclusions from your readings and findings?  Are you happy with your results?  What might you refactor or change in the future?

---

## References 🔗:
Link any useful resources you may have found throughout the day.

---

## Extra/Fun (Optional) 🎈🎉🥳:
Wen to the beach, sat in the sand and read my book for an hour. 🌎😀

**Comment by r002** [comment]
Cool!  What book are you reading?  Good so far?

**Comment by mccurcio** [comment]
Hey R,
The book is The Long Goodbye, by Raymond Chandler.
It is a very cool noir 50's crime novel. Humphrey Bogart played Marlowe on
the movies. ;D

**Comment by r002** [comment]
Neat!  I remember loving film noir back in college-- even took a few film classes back then on the subject.  Good memories! 😄

Bogart's great though-- loved him in _Casablanca_.  🤗
